import fs from "node:fs";
import path from "node:path";
import { simpleGit } from "simple-git";
import { Finding, GitProposal } from "../utils/types";

export interface RepoMeta {
  isGitRepo: boolean;
  branch?: string;
  latestCommit?: string;
  dirty?: boolean;
}

export async function collectRepoMeta(repoPath: string): Promise<RepoMeta> {
  try {
    const git = simpleGit(repoPath);
    const isRepo = await git.checkIsRepo();
    if (!isRepo) return { isGitRepo: false };
    const status = await git.status();
    const branch = status.current ?? undefined;
    const latestCommit = (await git.revparse(["--short", "HEAD"])).trim();
    return { isGitRepo: true, branch, latestCommit, dirty: !status.isClean() };
  } catch {
    return { isGitRepo: false };
  }
}

export function buildGitProposal(
  targetPath: string,
  findings: Finding[],
  dryRun = true,
  options?: { commitMessageTemplate?: string }
): GitProposal | undefined {
  if (findings.length === 0) return undefined;
  const high = findings.filter((f) => f.severity === "high").length;
  const branchName = `codebot/fix-${Date.now()}`;
  const prTitle = `Codebot: ${findings.length} quality findings suggestions`;
  const prBody = [
    "## Summary",
    `- Generated by Codebot for target: ${targetPath}`,
    `- Findings: ${findings.length} (high: ${high})`,
    "- This is a dry-run proposal by default.",
    "",
    "## Proposed changes",
    ...findings.slice(0, 20).map((f) => `- ${f.ruleId} in ${f.filePath}: ${f.fix?.patchPreview ?? f.suggestion}`)
  ].join("\n");
  return {
    repository: targetPath,
    branchName,
    commitMessage:
      options?.commitMessageTemplate ?? "chore(codebot): apply quality suggestions from automated scan",
    prTitle,
    prBody,
    changes: findings.map((f) => ({
      filePath: f.filePath,
      beforeSnippet: "existing code",
      afterSnippet: f.fix?.patchPreview ?? f.suggestion
    })),
    dryRun,
    metadata: { generatedAt: new Date().toISOString() }
  };
}

export function writeGitProposal(reportDir: string, sessionId: string, proposal: GitProposal): string {
  fs.mkdirSync(reportDir, { recursive: true });
  const filePath = path.join(reportDir, `${sessionId}-git-proposal.json`);
  fs.writeFileSync(filePath, JSON.stringify(proposal, null, 2), "utf8");
  return filePath;
}

export async function executeGitProposal(proposal: GitProposal): Promise<{
  branch: string;
  commit: string;
  planFile: string;
}> {
  const git = simpleGit(proposal.repository);
  const isRepo = await git.checkIsRepo();
  if (!isRepo) throw new Error("Cannot apply proposal: target is not a git repository");
  const status = await git.status();
  if (!status.isClean()) throw new Error("Cannot apply proposal: working tree is dirty");

  const protectedBranches = new Set((proposal.metadata?.protectedBranches as string[] | undefined) ?? []);
  if (protectedBranches.has(proposal.branchName)) {
    throw new Error(`Refusing to apply proposal on protected branch name: ${proposal.branchName}`);
  }
  const current = status.current ?? "";
  if (protectedBranches.has(current)) {
    // Current branch is protected. We still allow execution only on a separate local branch.
    if (proposal.branchName === current) {
      throw new Error("Refusing to apply changes directly on protected branch");
    }
  }
  await git.checkoutLocalBranch(proposal.branchName);

  const planDir = path.join(proposal.repository, ".codebot");
  fs.mkdirSync(planDir, { recursive: true });
  const planFile = path.join(planDir, "codebot-fix-plan.md");
  const content = [
    "# Codebot Fix Plan",
    "",
    `- Generated: ${new Date().toISOString()}`,
    `- Findings: ${proposal.changes.length}`,
    "",
    "## Planned Changes",
    ...proposal.changes.map((c) => `- ${c.filePath}: ${c.afterSnippet}`)
  ].join("\n");
  fs.writeFileSync(planFile, content, "utf8");

  await git.add([path.relative(proposal.repository, planFile)]);
  await git.commit(proposal.commitMessage);
  const commit = (await git.revparse(["--short", "HEAD"])).trim();
  return { branch: proposal.branchName, commit, planFile };
}
